CREATE TABLE SY_USER(
	NO INT NOT NULL AUTO_INCREMENT,
    ID VARCHAR(15) NOT NULL UNIQUE,
    PW VARCHAR(15) NOT NULL,
    NAME VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(100),
    PRIMARY KEY (NO)
);

INSERT INTO SY_USER(ID, PW, NAME, EMAIL) VALUES('test', 'test', '테스터', 'test@test.com');